### ISSUE TITLE
Web page not available 

### ISSUE THREAD

**Issue by AndreasPetersen** [mrothberg/Kakumei-for-WaniKani#4]
I get the following error when opening reviews:

![Screenshot_20230328-133220](https://user-images.githubusercontent.com/2496648/228128953-7d3afacc-f3d5-4daa-bb17-1012dc7e082f.png)

A similar error occurs when opening the lessons page.

Is this error related to this change: https://community.wanikani.com/t/updates-to-lessons-reviews-and-extra-study-are-live/61049 ?

**Comment by starkgate** [comment]
Had this issue as well, but it's working now. I assume it was more an issue with the website than the app.

**Comment by AndreasPetersen** [comment]
I can confirm that it's working again
